services:
  frontend:
    image: system256/time-app-frontend-dev
    restart: always
    ports:
      - 3000:3000
  api:
    image: system256/time-app-api-dev
    restart: always
    ports:
      - 5555:5000
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB:  ${MYSQL_DB}
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data_pub:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  mysql_data_pub: