services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build: ./api
    restart: always
    ports:
      - 5555:5000
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  mysql_data: